// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLR1mma31TfsudGzchxi65R-PfRRigTck',
    appId: '1:999105837304:web:60879cb60fbaf6dd56230d',
    messagingSenderId: '999105837304',
    projectId: 'crudwecode',
    authDomain: 'crudwecode.firebaseapp.com',
    storageBucket: 'crudwecode.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARP_GstsDTg57fGyPc7OTff8z9V7pyHAI',
    appId: '1:999105837304:android:ee6b9d097f05598856230d',
    messagingSenderId: '999105837304',
    projectId: 'crudwecode',
    storageBucket: 'crudwecode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzmDfr6o9kwsHjs8QH88irgOHqYv2_h0',
    appId: '1:999105837304:ios:500aa5cc9f76d74056230d',
    messagingSenderId: '999105837304',
    projectId: 'crudwecode',
    storageBucket: 'crudwecode.appspot.com',
    iosClientId: '999105837304-ga3giulj63rgt7op6hp1l9308ke4nku2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecodeFirebaseFlutterb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfzmDfr6o9kwsHjs8QH88irgOHqYv2_h0',
    appId: '1:999105837304:ios:500aa5cc9f76d74056230d',
    messagingSenderId: '999105837304',
    projectId: 'crudwecode',
    storageBucket: 'crudwecode.appspot.com',
    iosClientId: '999105837304-ga3giulj63rgt7op6hp1l9308ke4nku2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecodeFirebaseFlutterb',
  );
}
